Node: New setLogEventListeners() utility to get log events
### Details

- Instead of relying on `DEBUG` variable and stdout/stderr logs, an application may want to collect mediasoup generated logs and post them somewhere.
- This PR exposed a new `setLogEventListeners()` function at mediasoup root module level.

### Usage example

```ts
mediasoup.setLogEventListeners({
  ondebug: undefined,
  onwarn: (namespace: string, log: string) => {
    MyEnterpriseLogger.warn(`${namespace} ${log}`);
  },
  onerror: (namespace: string, log: string, error?: Error) => {
    if (error) {
      MyEnterpriseLogger.error(`${namespace} ${log}: ${error}`);
    } else {
      MyEnterpriseLogger.error(`${namespace} ${log}`);
    }
  }
});
```